
kind: Service
apiVersion: v1
metadata:
  name: nfs-service
  namespace: default
spec:
  selector:
    role: nfs
  clusterIP: "10.152.183.70" # <---- make sure this is within --service-cluster-ip-range of the api-server
  ports:
    # Open the ports required by the NFS server
    # Port 2049 for TCP
    - name: tcp-2049
      port: 2049
      protocol: TCP
    # Port 111 for UDP
    - name: udp-111
      port: 111
      protocol: UDP

---

# Run the NFS server image in a pod that is
# exposed by the service.

kind: Pod
apiVersion: v1
metadata:
  name: nfs-server
  namespace: default
  labels:
    role: nfs
spec:
  containers:
    - name: nfs-server-container
      image: cpuguy83/nfs-server
      securityContext:
        privileged: true
      args:
        # make sure to use /exports to avoid the error exportfs: /var/nfs does not support NFS export
        - /exports