apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
  labels:
    app: counter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
      name: counter
    spec:
      containers:
      - image: akanso/counter:0.1
        imagePullPolicy: IfNotPresent
        name: counter
        command:
        - "/counter"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to ETCD_ENDPOINTS
              name: etcd-config
              # Specify the key associated with the value
              key: endpoints
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 20
        lifecycle:
            preStop:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    'for i in {3..1}; do echo "I am starting shutdown in $i sec..."; sleep 1; done',
                  ]
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "0.5Gi"
      terminationGracePeriodSeconds: 45
                  
